### ISSUE TITLE
Vasco

### ISSUE THREAD

**Issue by Synzinho** [Dryrtan/Spotify-Download-Telegram-Bot#3]

**Comment by Dryrtan** [comment]
<img src="https://media.tenor.com/Jt3M6vDQsFUAAAAC/breh-caleon.gif" width="30%" height="30%">

**Comment by Dryrtan** [comment]
**O Vasco acha que é Telesena, que ganha quem faz menos pontos**

**Comment by Synzinho** [comment]
Kkkkkkkkk , foi mal mano qualquer coisa é que tô aprendendo a mexer no
github

Em qua, 1 de nov de 2023 07:11, Dryrtan ***@***.***> escreveu:
